ci: run integration tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,11 +46,11 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v4
 
-      - name: Set up Node
+      - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
-          cache: npm
+          cache: "npm"
 
       - name: Install dependencies and run tests
         run: npm install-ci-test
@@ -66,10 +66,39 @@ jobs:
         with:
           dockerfile: Dockerfile
 
+  integration-tests:
+    name: Integration Tests
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        node-version: [lts/iron]
+
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v4
+
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: "npm"
+
+      - name: Install node dependencies
+        # NOTE: we need to install dev dependencies too vs. production only for hurl
+        run: npm install
+
+      - name: Build Containers
+        run: docker compose up -d
+
+        # Print the logs if the tests fail
+      - name: Run Hurl Tests
+        run: npm run test:integration || (docker compose logs; exit 1)
+
   docker-build:
     name: Build Docker image
-    # Don't bother running this job unless the other three all pass
-    needs: [lint, dockerfile-lint, unit-tests]
+    # Don't bother running this job unless the other four all pass
+    needs: [lint, dockerfile-lint, unit-tests, integration-tests]
     runs-on: ubuntu-latest
     steps:
       # Set up buildx for optimal Docker Builds, see:
